AWSTemplateFormatVersion: 2010-09-09
Description: CI/CD pipeline for github projects
Resources:
AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  myDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "firstname"
          AttributeType: "S"

      KeySchema: 
        - 
          AttributeName: "firstname"
          KeyType: "HASH"

      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "assingment_table" 