AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with cfn-response .
Resources:
  myfunc:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.7
      Handler: index.handler
      Code:
        ZipFile: |
            import os
            import boto3
            from datetime import datetime
            def handler(event, context):
              print(event)
              print('My Test code here')
              job_start = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
              print(job_start)
      Description: Invoke a function during stack creation
      Role: arn:aws:iam::333974312216:role/lambda-full-role
      
