AWSTemplateFormatVersion: 2010-09-09
Description: CI/CD pipeline for github projects
Resources:
AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  myDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "firstname"
          AttributeType: "S"
        - 
          AttributeName: "lastname"
          AttributeType: "S"
        - 
          AttributeName: "telephone"
          AttributeType: "S"
        - 
          AttributeName: "telephonepassword"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "firstname"
          KeyType: "HASH"
        - 
          AttributeName: "lastname"
          KeyType: "RANGE"
        - 
          AttributeName: "telephone"
          KeyType: "RANGE"
        - 
          AttributeName: "telephonepassword"
          KeyType: "RANGE"          

      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "assingment_table1" 