AWSTemplateFormatVersion: 2010-09-09
Description: CI/CD pipeline for github projects

Resources:
AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  myDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "FirstName"
          AttributeType: "S"
        - 
          AttributeName: "LastName"
          AttributeType: "S"
        - 
          AttributeName: "Telephone"
          AttributeType: "S"
        - 
          AttributeName: "TelephonePassowrd"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "FirstName"
          KeyType: "HASH"
        - 
          AttributeName: "FirstName"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "assingment_table"